### ISSUE TITLE
[Question] Release ?

### ISSUE THREAD

**Issue by KaKi87** [samicrusader/qomui#6]
Hello,

If you fixed support for latest distros, could you please publish a release ?

Especially `AppImage` or `deb`.

Thanks

**Comment by samicrusader** [comment]
I am not sure about AppImage, as one of it's qualities is not requiring root permissions (needed for the service which handles things relating to iptables (split-tunnel, killswitch, multihop), but correct me if I'm wrong), but I will take a look at packaging it for Debian.

**Comment by KaKi87** [comment]
> correct me if I'm wrong

I honestly have no idea.

> I will take a look at packaging it for Debian.

Thanks.

Another kind of single-file binary would be enough, although I prefer something that automatically creates and deletes start menu entries instead of having to handle `.desktop` files myself.

**Comment by samicrusader** [comment]
wrote a script to package it for debian, getting a test environment setup now
![image](https://user-images.githubusercontent.com/89530830/189784326-45b06dd2-506b-4f22-b9c9-1a4fb9b289b5.png)

**Comment by samicrusader** [comment]
https://github.com/samicrusader/qomui/releases/tag/v0.8.4

killswitch works and multihop works (current release requires net-tools to be installed, i'll handle that in another release)

**Comment by KaKi87** [comment]
I was able to install it, thanks. However, I can't find NordVPN in the provider list ?
EDIT : I'm also getting "dbus error" notifications.

**Comment by samicrusader** [comment]
dbus errors may be handled by restarting the system but I'd have to look into that more.
NordVPN wasn't supported in the original project and my subscription to that expired, but I'll look into adding it if I resubscribe (I've been using Windscribe more).

**Comment by KaKi87** [comment]
That's strange, because searching for a Linux NordVPN GUI is how I found this project. 🤔
